import pytest

from app.routing import classify_intent


@pytest.mark.parametrize(
    "message,intent",
    [
        ("What were total sales last month?", "sales"),
        ("profit on orders this quarter", "profit"),
        ("wholesale pricing please", "general"),  # "who" must not match inside "wholesale"
        ("costume stock levels", "inventory"),
        ("who is customer #42", "customer"),
        ("top customers by revenue", "customer"),
        ("which customers placed the most orders", "customer"),
        ("Who are our best-selling brands?", "sales"),
        ("Can you lookup inventory for SKU 123?", "inventory"),
        ("Hi, who are you?", "general"),
        ("Give me the contact number for warehouse Pune", "inventory"),
        ("Which products are running low and need reorder?", "inventory"),
        ("contact details for Priya Sharma", "customer"),
        ("Rahul Verma's phone number", "customer"),
        ("What's the shipping cost to Mumbai?", "general"),
        ("How do I request a refund?", "general"),
        ("Is customer support available on weekends?", "general"),
        ("How do I see revenue for last week?", "sales"),
        ("How can I find our top customers?", "customer"),
        ("What was total shipping cost last month?", "profit"),
        ("Where is my order?", "general"),
        ("What's the status of my order 1234?", "general"),
        ("I want to cancel my order", "general"),
        ("Can I get a refund for a damaged item?", "general"),
        ("Which SKUs need restocking?", "inventory"),
        ("my order is late by a week", "general"),
        ("my order arrived damaged today", "general"),
        ("track my order placed yesterday", "general"),
        ("I want a refund for my order from last month", "general"),
        ("my order volume this week", "sales"),
        ("refund for order #12 last month", "general"),
        ("where is order 55", "general"),
        ("order number 5", "general"),
        ("show me order ORD-9 total", "general"),
        ("cancel order 5 how many", "general"),
        ("top 10 orders", "sales"),
        ("order no. 5 status", "general"),
        ("refund for order no 7", "general"),
        ("status of order ORD123", "general"),
        ("has order 55 shipped", "general"),
        ("details of order 55", "general"),
        ("orders last month", "sales"),
        ("how do I check low stock items", "inventory"),
        ("how do i view profit margins", "profit"),
        ("how can i see inventory", "inventory"),
        ("how do I find customer 42", "customer"),
        ("how do I see orders in may", "sales"),
        ("How do I cancel an order placed this week?", "general"),
        ("How do I return an order from last month?", "general"),
        ("What is the refund policy for orders this year?", "general"),
        ("How can I check if this is available?", "general"),
        ("Cancel order 77", "general"),
        ("Are refunds processed within 7 days?", "general"),
        ("What does it cost to ship to Chennai?", "general"),
        ("Is the Samsung TV available for delivery to Pune?", "general"),
        ("orders delivered to Delhi last week", "sales"),
        ("track order 123", "general"),
        ("show me order 123 status", "general"),
        ("what's the cost of shipping", "general"),
        ("show orders for CUST000042", "customer"),
        ("how much did we sell yesterday", "sales"),
        ("do you deliver to Guwahati", "general"),
        ("hello there", "general"),
        ("", "general"),
    ],
)
def test_classify_intent(message, intent):
    assert classify_intent(message) == intent
